[project]
name = "sml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.13"
dependencies = [
    "datasets>=5.0.0,<6.0.0",
    "lm-eval[api]>=0.4.12,<1.0.0",
    "mlx>=0.32.0,<1.0.0",
    "numpy>=2.4.6,<3.0.0",
    "pytest>=9.1.1,<10.0.0",
    "sentencepiece>=0.2.1,<1.0.0",
    "torch>=2.13.0,<3.0.0",
    "zstandard>=0.25.0,<1.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.21,<16.0.0",
]

[tool.uv]
required-version = ">=0.9.17"
exclude-newer = "7 days"

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "sml"
module-root = "v2/src"
